### ISSUE TITLE
save summary of which files were selected (and why) [was: identify which pages have multiple scans and choose which one to keep]

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#1]
How do we want to handle the multiple scans in the `raw` folder?

**Comment by nicholasjhorton** [comment]
For example, page 314 and 314b are two images of the same page. In these situations, how to proceed?

**Comment by nicholasjhorton** [comment]
Here are the files that have b suffixes as well as the handful with c suffixes (three images).

```
[MATH-ML-013839:Imaging/Parsons_Ledger/raw] nicholashorton% ls *b.CR2
005b.CR2	018b.CR2	077b.CR2	099b.CR2	177b.CR2	303b.CR2	386b.CR2	394b.CR2
006b.CR2	067b.CR2	093b.CR2	171b.CR2	286b.CR2	314b.CR2	388b.CR2
[MATH-ML-013839:Imaging/Parsons_Ledger/raw] nicholashorton% ls *c.CR2
005c.CR2	006c.CR2
```

**Comment by LorraineOloo** [comment]
- Look through the photos and select the one with highest resolution
- Rename the files to a and b and c

**Comment by NahiaP** [comment]
Removed doubles for pages 171-394.

**Comment by nicholasjhorton** [comment]
Thanks! Can you please add some additional details about which image was selected (and why)?

**Comment by NahiaP** [comment]
Currently taking notes on why pages were deleted. Will also explain the renaming of one page with the corner ripped out in future comment very soon.

**Comment by LorraineOloo** [comment]
Removed doubles for pages 1-170. The criteria I used for selecting the images was the one with the highest resolution.

**Comment by NahiaP** [comment]
Bent page: 286, 177, 388

Missing scrap papers: 303

Lighting: 171, 314

Crooked Page: 386

Additionally, the ‘multiple scan’ for page 394 was misclassified. The top corner of the page in that photo was ripped and so the page number seen was 394 but the page itself was unlabeled. I relabeled it as 396 as it was the only possible page.

**Comment by nicholasjhorton** [comment]
@LorraineOloo and @NahiaP thanks for your work on this front! 

I've reopened this with a new title (and unassigned you both!) just to ensure that we don't lose the excellent meta-data guidance that you have collated.
