### ISSUE TITLE
request spreadsheet template and start to populate it

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#12]
A spreadsheet template that can be used to create metadata records conforming to the Digital Commonwealth metadata guidelines and used for batch upload of records and objects into the Digital Commonwealth repository is available upon request

**Comment by nicholasjhorton** [comment]
@sedelson31 and @Cheafitz25 do you have any updates on the status of this issue?

**Comment by nicholasjhorton** [comment]
@sedelson31 is working to draft a message for @nicholasjhorton to review that we can eventually send to Eileen Crosby. We will probably want to cc Zoe Jacobs from CCE.

Proposed timeline: Monday draft? Tuesday email Eileen?

**Comment by sedelson31** [comment]
@nicholasjhorton here is the draft

Hi Eileen,

I hope you are doing well. I am Sarah Edelson, a student in the Amherst College course “Mining the History of Holyoke.” As a Digital Commonwealth partner institution, we were wondering if you have a list of the metadata requirements that we will need to follow to have the documents we are working with accepted by the archive. Additionally, the Digital Commonwealth website states that there is a metadata spreadsheet that we could use as a template to fill in, and if you have that could you pass along as well? Lastly, we would appreciate any insight into how you standardize cropping across hundreds of pages of one document.

Thank you very much for all of your assistance - we are looking forward to sharing our progress with you!

Best,
Sarah Edelson

**Comment by nicholasjhorton** [comment]
Sarah, this looks great! Can you please cc me and Zoe Jacobs with your message?


On Feb 11, 2023, at 3:07 PM, sedelson31 ***@***.***> wrote:


@nicholasjhorton here is the draft

Hi Eileen,

I hope you are doing well. I am Sarah Edelson, a student in the Amherst College course “Mining the History of Holyoke.” As a Digital Commonwealth partner institution, we were wondering if you have a list of the metadata requirements that we will neet to follow to have the documents we are working with accepted by the archive. Additionally, the Digital Commonwealth website states that there is a metadata spreadsheet that we could use as a template to fill in, and if you have that could you pass along as well? Lastly, we would appreciate any insight into how you deal with cropping images.

Thank you very much for all of your assistance - we are looking forward to sharing our progress with you!

Best,
Sarah Edelson

**Comment by sedelson31** [comment]
Just received a response from Digital Commonwealth, and I have attached the PDF and 2 excel spreadsheets they sent me.
[DC-BPL_MODS_Guidelines_June2022.pdf](https://github.com/STAT210-S23/Parsons_Paper_Register/files/10734182/DC-BPL_MODS_Guidelines_June2022.pdf)
[MODS-ColumnHeaders_Template.xls](https://github.com/STAT210-S23/Parsons_Paper_Register/files/10734183/MODS-ColumnHeaders_Template.xls)
[MODS-ColumnHeaders_UsageGuidelines.xls](https://github.com/STAT210-S23/Parsons_Paper_Register/files/10734184/MODS-ColumnHeaders_UsageGuidelines.xls)

**Comment by nicholasjhorton** [comment]
That's great. Can you please add these into the repo in a new `digital_commonwealth` folder?

**Comment by sedelson31** [comment]
done

**Comment by nicholasjhorton** [comment]
@sedelson31 thanks!

Might you be willing to start to review and identify what information we will need to pull together? This might include materials that we all need to read.

You might start with this issue and create a Quarto file if needed.

**Comment by sedelson31** [comment]
just added https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/Metadata.qmd

**Comment by nicholasjhorton** [comment]
Closing because Eileen Crosby is taking over next steps for the accession to the Digital Commonwealth.
