### ISSUE TITLE
Add .DS_Store to git.ignore

### ISSUE THREAD

**Issue by NahiaP** [STAT210-S23/Parsons_Paper_Register#14]
Remove https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/.DS_Store file and add new rule to the https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/.gitignore

**Comment by nicholasjhorton** [comment]
Fixed via https://github.com/STAT210-S23/Parsons_Paper_Register/commit/ecc4fbcfe4874b7d4bbaf92546e643fa849810b1 @annajzhou
