### ISSUE TITLE
Figure out guidelines for cropping

### ISSUE THREAD

**Issue by sedelson31** [STAT210-S23/Parsons_Paper_Register#15]

**Comment by nicholasjhorton** [comment]
How do we determine what cropping and/or image adjustment will be needed?

See for example 
![](https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/jpg/001.jpg)

**Comment by nicholasjhorton** [comment]
I wonder if this is something that we could ask Eileen Crosby about? @sedelson31 might you be willing to incorporate this into your draft letter?

**Comment by nicholasjhorton** [comment]
My sense is that we should use common sense and ensure that all edges show up in the cropped image. Does that sound reasonable @kjinsanity and @NahiaP?

I will close this issue.
