### ISSUE TITLE
scan missing page and rescan muddled scans

### ISSUE THREAD

**Issue by sedelson31** [STAT210-S23/Parsons_Paper_Register#16]

**Comment by nicholasjhorton** [comment]
- page 254: may need to be rescanned, see https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/README.md

**Comment by nicholasjhorton** [comment]
also want to look out for particularly blurry or otherwise problematic pages.

**Comment by nicholasjhorton** [comment]
- 249 (see https://github.com/STAT210-S23/Parsons_Paper_Register/issues/2)
- 254
- 287 (see https://github.com/STAT210-S23/Parsons_Paper_Register/issues/2)
- 320
- 338
- 368

**Comment by nicholasjhorton** [comment]
@nicholasjhorton has taken (low-res) additional scans and will work to integrate these into the Shared Drive and https://github.com/STAT210-S23/Parsons_Paper_Register/tree/main/jpeg folder.

**Comment by nicholasjhorton** [comment]
Done via https://github.com/STAT210-S23/Parsons_Paper_Register/commit/0d70f8cc2a878bccda60fbc04a32a775b785b50c
