### ISSUE TITLE
review Hickey thesis for linkages and connections with the Parsons Register

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#17]
This is an offshoot of https://github.com/STAT210-S23/Parsons_Paper_Register/issues/7

Are there results or findings from the Hickey masters thesis that are relevant for the analysis of employee trends at the Parsons Paper Company from 1861 to 1869?

This issue will be closed when some connections are added to the Quarto file (and pdf) in https://github.com/STAT210-S23/Parsons_Paper_Register/tree/main/payroll_analysis

**Comment by sedelson31** [comment]
@nicholasjhorton do you have the link to the thesis?

**Comment by nicholasjhorton** [comment]
It can be found on the class Moodle site (under readings).

**Comment by sedelson31** [comment]
The thesis mainly focuses on the Holyoke paper industry from 1899-1951, but I added a few quotes to the qmd file that may be of relevance when examining 1860s employment.

**Comment by nicholasjhorton** [comment]
@sedelson31 this is great, thanks! For reference, here are the commits that you made: 64135914b2630aaa69228f0a31f6e025a249a00b, 
7384932af39d03d8c3a78f04f40159cd2c7b12b7, https://github.com/STAT210-S23/Parsons_Paper_Register/commit/583b8202502b6fa460e6f91de3c6289d45960f6a, and c9c19cc602689d735bf1a59b911ce68a5a30599c

I've asked people to read chapters 1 (pre-1900 history) and 5 (economics of the paper industry) but will close this.
