### ISSUE TITLE
orient tiff files and adjust color balance, rotate, and crop images for register scans (was identify workflow to create tiff file and orient page in the correct direction)

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#2]
These files will be sources from the `raw` folder and added to the `tiff` folder

**Comment by nicholasjhorton** [comment]
Would the GIMP (graphical image manipulation project) be helpful here? https://www.gimp.org

Someone (Tim?) asserted that one can automate Photoshop to do this. Amherst owned computers (e.g., in the computer lab in Frost?) have Photoshop installed on them.

**Comment by nicholasjhorton** [comment]
This sort of needs to wait on #1 (but we can explore in the interim).

**Comment by NahiaP** [comment]
For orienting the images, once they are in the right format, divide them into odds and evens and Photoshop has a way to bulk rotate them that may work based on this Stack Exchange post [https://graphicdesign.stackexchange.com/questions/133831/how-to-batch-rotate-image-to-make-them-all-landscape#:~:text=Drop%20the%20images%20into%20a,Done.](url)

**Comment by nicholasjhorton** [comment]
@NahiaP thanks for your detective work.

Can the three of us try to brainstorm what a workflow might look like given our setup? I'm assuming:

1. all of us can install Google Drive for Desktop so we have access to the files locally [DONE?]
2. we figure out how to convert from the raw to tiff format [DONE]
3. we try to automate the rotation
4. we manually adjust colors
5. we manually crop
6. we output the high quality jpg files
7. we add the jpg files to GitHub

This is the most time critical of any of our pending issues I believe. Any chance that we could try to update this issue and/or briefly Zoom at some point today or (not optimal but may be helpful) over the weekend?

**Comment by nicholasjhorton** [comment]
I've managed to convert all of the raw files to tiff files on Google Drive (see #19 for some loose ends). Can you please review the `tiff` folder and let me know if you see any issues?

I've relabeled this issue to focus on orienting the pages and converting the color balance. Ideally we can find a workflow to automate some of this. If not, we'll need to roll up our sleeves and work through the pages manually.

One idea to throw into the mix: create a `tiff_temp` folder that is a copy of the full `tiff` folder and gradually work through those files and add them to a `tiff_final` folder.

**Comment by kjinsanity** [comment]
February 14th, 2023 Meeting Notes:

Created an initial protocol to rotate, crop, and color adjust tiff files on the shared Google Drive

Protocol: 

1. Copy all photos from `tiff` folder to `tiff_processing`. These copied pictures will have the name "Copy of XXX.tiff"
2. Using Finder, we will rotate image, crop until there is around 1 cm margins (look at the model file in `tiff_adjusted` folder), and auto-enhance the brightness levels
3. After saving the edits, rename the file to just "XXX.tiff" to know when it is completed

We will also need to create function from #20 in order to make sure we are not missing pictures.

**Comment by NahiaP** [comment]
Currently in process of moving the copies of tiff files into tiff_processing

**Comment by NahiaP** [comment]
All copies of tiff files now in the tiff_processing folder.

**Comment by nicholasjhorton** [comment]
Thanks @nahiap!

Here's my proposal for next steps:

- @nicholasjhorton converts pages 000-150
- @nahiap converts pages 151-280
- @kjinsanity converts pages 281-396

By convert, I mean:

1. starting with `Copy of XXX.tiff` from `tiff_processing` folder, rotate page
2. crop so that excess is removed (but all edges remain)
3. adjust colors
4. save in `XXX.tiff`

@kjinsanity: it sounds like the Macs on the first floor of SMudd are set up with Preview and the Google Drive desktop app. Can you please find a time to test the setup on your end to see if that works?

Slemp, Christopher M. commented on this incident on Feb 15, 2023 - 9:03am
--
Hi Nick,The iMacs in the CCT (on the first floor of SMudd around the Help Desk) are powerful and have the Google Drive desktop app installed already.  I can install additional apps on one or more of those computers as necessary.

**Comment by NahiaP** [comment]
I tested out converting 20 pages and it took me about 20 minutes. Accounting for improving the process and not having my small coughing fit, that speed should be reduced. I'll begin working on my set of pages and update once I finish.

**Comment by NahiaP** [comment]
Pages 151-280 converted.

Two notes:

- 253 has a duplicate (253 and 253-old)
- 249 is a bit blurry

**Comment by kjinsanity** [comment]
Thanks for the update on the Macs! 

I haven't had time to check in with it yet, but I'll be sure to reorient and modify pages 281-396 as requested later this week. I will provide a further update as I proceed

**Comment by nicholasjhorton** [comment]
I've been making slow but steady progress with my set. I've noticed some corrupted images in the `tiff_processing` folder which has required me to copy the originals from `tiff_original`. See `Copy of 375.tiff` that I see as corrupted. @kjinsanity when you dive back into your remaining conversions, can you please keep an eye out for this?

**Comment by nicholasjhorton** [comment]
I've figured out the corrupted image issue (it was a problem on my end).

@kjinsanity can you please continue to process your remaining files as you have time?  Thanks in advance, Nick

**Comment by nicholasjhorton** [comment]
@NahiaP Kevin writes: I’ve been trying to use the iMacs to open up the files, but it has not been working. I tried different solutions like syncing with my google drive app but not only has it been really slow (as they aren’t preemptively synced) but I get errors like this or in the safari browser for some reason

Might you be in a position to help with the tiff wrangling for some of the remaining files? I can also help with this.

@kjinsanity might you be willing to pivot to work on #26 and https://github.com/STAT210-S23/Parsons_Paper_Register/issues/20?

**Comment by NahiaP** [comment]
I can help with the remaining tiff files, I'll see how many I can get done tonight and provide updates as I go.

**Comment by NahiaP** [comment]
Remaining tiff files all processed. A couple of notes:

- 287,338 a bit blurry
- 320 bent and blank

**Comment by nicholasjhorton** [comment]
Thanks! This is greatly appreciated. I will convert to jpeg later this morning.

I've added the list of funky pages to https://github.com/STAT210-S23/Parsons_Paper_Register/issues/16
