### ISSUE TITLE
Write Function to Search for Missing Parson's Paper page numbers

### ISSUE THREAD

**Issue by kjinsanity** [STAT210-S23/Parsons_Paper_Register#20]
Enumerate from 000 to 396 and output the missing values. This should match the pages we know are missing

**Comment by nicholasjhorton** [comment]
My thought:

- function which takes arguments `suffix` and `pathname`
- it generates a vector from 0:396
- it creates a character vector from "000" to "396"
- it prepends the pathname, "/", number, then appends the suffix
- it calls `file.exists()` for each file returns those that don't exist.

Hopefully this should match the list in https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/README.md

Shall I proceed with the implementation?

**Comment by kjinsanity** [comment]
I was working on creating this method, and I also used some of the ideas presented above as well to create a test function that seems to have the desired output. 

Will run this function on the modified .tiff files after further examination

**Comment by nicholasjhorton** [comment]
@kjinsanity can you please run the function on the files in https://github.com/STAT210-S23/Parsons_Paper_Register/tree/main/jpeg?

**Comment by kjinsanity** [comment]
Comparing the output of my function (from this [file ](https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/missing_pages_results/Missing-Page-Number-Function.pdf) to the list mentioned above, we are missing a few images. More specifically, it seems that 371-376 and 395 are missing for now

**Comment by nicholasjhorton** [comment]
This is most helpful. I've tracked down those loose ends. Can you please run one more time then close the issue? I'm suspecting that the only missing pages will then be:

- 254 (we think that this is in the register)
- 255-256 (missing page, known issue)
- 309-312 (missing pages, known issue)

It would be helpful to include a brief discussion of this issue (and your code) in #26

**Comment by kjinsanity** [comment]
Screenshotted my results below, it seems that we are still missing pages 368 and 395

![image](https://user-images.githubusercontent.com/10384016/220427713-32584f8e-118a-4b41-ac91-b166ff0085f7.png)

**Comment by nicholasjhorton** [comment]
368 seems to be missing. I've added it to #16.

I've tracked down 395. Thanks again for your work on this front!
