### ISSUE TITLE
Create example of nicely formatted table using Quarto

### ISSUE THREAD

**Issue by annajzhou** [STAT210-S23/Parsons_Paper_Register#21]

**Comment by nicholasjhorton** [comment]
See https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/example-fig-tables.qmd @annajzhou @NahiaP @Cheafitz25 @LorraineOloo @sedelson31 @kjinsanity 

Closed via https://github.com/STAT210-S23/Parsons_Paper_Register/commit/a5d3793047a1f0708c4fa0d0ba36e2f4d2df2664
