### ISSUE TITLE
identify next steps or additional work on Parsons Paper ancestry.com project

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#23]
This issue will be closed when next steps (potentially in new issues) are identified to finish up work on the Parsons Paper ancestry.com initiative.

This will want to include:

- [ ] exploration of any additional questions to explore
- [ ] incorporating comments or suggestions that Eileen might offer
- [ ] drafting a (short) presentation for May 9th

See also #5

**Comment by nicholasjhorton** [comment]
Some issues I see in the current draft https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/addresses_exploration/workers_database.pdf

- need page numbers in Figure 1 caption, Figure 5 caption, and Figure 8 caption
- I would encourage you to weave in the numbers that you have from the sample Figure (as I did for page 253). You are trying to tell a story about these people. In particular, what else do you know about Lucy and E.A. Allen? Were they able to sign their names? How did their pay compare to other women? To other people on that page? Is this only page where you can find them? 
- Perhaps move Figure 2 to the Appendix?
- Move the Ancestry info to a Table that displays the results in a more easy to understand way?

**Comment by nicholasjhorton** [comment]
Do you have a punch list for next steps for the report? As you know, the draft is due on Friday. I'd be glad to take a look at anything in advance of class I can do so if you add a comment to this issue by noon on Thursday.

My main suggestions are to:
- to consider the audience (people from Holyoke interested in industrial history?) 
- separate the technical appendix (helpful details about ancestry.com and your work behind the scenes)
- adding a simple map of where some of the people you've tracked down lived (I can assist here).

Overall this is coming along well but further polishing and refinement will be helpful.

**Comment by Cheafitz25** [comment]
Hello Professor, Lorraine and I will work to incorporate your edits and suggestions along with Eileen's. I think we can write more about the Allen family given what we discovered on the field trip. Additionally, we can divide the report into two sections; the first would detail the Allen family and the registry. The second section will be the technical aspects such as how we found the information using Ancestry.com. I think for your suggestion of adding a map, we may need help.

**Comment by nicholasjhorton** [comment]
This sounds like an excellent plan.

In terms of mapping, I'd be glad to assist. See https://rstudio.github.io/leaflet/

```
library(tidyverse)
library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map
```

**Comment by nicholasjhorton** [comment]
I've pushed the pdf of the updated Quarto file.

**Comment by nicholasjhorton** [comment]
But I see that it hasn't changed much: I'll hold off on my review.

**Comment by nicholasjhorton** [comment]
Happy Friday!

Can you please:

1. share an update on what you've been working on since we met yesterday, and
2. add a comment for me in this issue when you are ready for my review?

**Comment by nicholasjhorton** [comment]
I've shared feedback under separate cover. Can you please revise and close this issue (anytime before the end of the day on Monday, March 27th)?

**Comment by nicholasjhorton** [comment]
@LorraineOloo wrote: We are unable to directly include the locations on the map if we want to print a pdf. If we set print to html only, then it is possible to include the addresses. Please let us know how you wnat us to proceed.

Is the issue that you are using leaflet to generate your maps? If so, I would suggest moving to openstreetmap or similar interface to `ggmap` to allow you to directly generate a PDF. There are some examples in https://mdsr-book.github.io/mdsr2e/ch-spatial.html

**Comment by nicholasjhorton** [comment]
final revision to Parsons Paper Company reports due by the end of the day on Wednesday, March 29th: can you please let me know if you have any questions as you finish up your work? @LorraineOloo and @Cheafitz25?

**Comment by nicholasjhorton** [comment]
Are you all set for me to proceed with my review? Thanks in advance for any guidance, Nick

**Comment by Cheafitz25** [comment]
Yes apologies, I will close the issue now.

**Comment by nicholasjhorton** [comment]
I'm unable to read the file: can you please confirm that the pdf you pushed (https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/addresses_exploration/workers_database.pdf) is valid? Thanks in advance, Nick

**Comment by LorraineOloo** [comment]
It should be fixed now.
