### ISSUE TITLE
revisions of the summary of workers over time in the Parsons register

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#24]
This issue will be closed when next steps (potentially in new issues) are identified to finish up work on the Parsons Paper summary of workers over time initiative.

This will want to include:

- [ ] exploration of any additional questions to explore
- [ ] incorporating comments or suggestions that Eileen might offer
- [ ] drafting a (short) presentation for May 9th

See also #7

**Comment by sedelson31** [comment]
added the intro to the qmd file - can someone else please render it to a pdf?

**Comment by nicholasjhorton** [comment]
I had a chance to review https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/payroll_analysis/parsons_payroll.pdf and it is shaping up well. Some initial suggestions:

- Title is cryptic
- Need a bit more introduction before you jump into "How many days in a pay period". What is the Parsons Paper Company? Where is it located? What is the register? Where is it located? When was it scanned? You might mention that the class is working to make these and related materials more accessible.
- It would be helpful to include the sample page that I picked (page 253) and display it to orient people to the register.
- You can and should bring in some of the analyses that I shared  in class (see notes from `STAT210-2023-02-02.qmd`: you can any or all of that)
- Then I suspect that you can start to work through your questions
- The three images are hard to read. Can you focus on 223 and 261 to start (and include 224, 225, 262, and 263 in an appendix?).
- Some of your answers are a bit cryptic (e.g., "Counted 92 employees"). Can you elaborate and provide a bit more guidance for the reader?
- I would suggest using "we" instead of "I".
- Need captions for all figures.
- Close with next steps and future work?

**Comment by annajzhou** [comment]
I updated the qmd + pdf with the suggestions and edits incorporated -- sorry about the confusion, I don't think my last push from Friday went through so the newest version wasn't updated until now

**Comment by nicholasjhorton** [comment]
Do you have a punch list for next steps for the report? As you know, the draft is due on Friday. I'd be glad to take a look at anything in advance of class I can do so if you add a comment to this issue by noon on Thursday.

My main suggestion is to consider the audience (people from Holyoke interested in industrial history?) and to work to link your analyses with the register pages. It's coming along well but further polishing and refinement will be helpful.

**Comment by nicholasjhorton** [comment]
Can the currency information (even as an unanswered question) from #4 be woven into your report? It's mostly linear (see my lecture notes from early on).

**Comment by nicholasjhorton** [comment]
Happy Friday!

Can you please:

1. share an update on what you've been working on, and
2. add a comment for me in this issue when you are ready for my review?

**Comment by sedelson31** [comment]
We added a table from one of the documents that Eileen shared with us that shows the weekly wages of MA Paper Workmen for 1860, 1872, and 1878, and then displayed these data on a bar graph. We then looked at the first few pages of the register and calculated the weekly wages of different Parsons jobs in 1861, put this information in a spreadsheet, and displayed it via a kable table and a bar graph. Then we added some analysis where we discussed the difference in wages between Parsons and the greater MA Holyoke paper industry and also discussed how some of the wages may have differed based on information from the Hickey thesis.

@annajzhou is going to check over the formatting tonight  and then we will be ready for your review. Also - one problem is that the graphs, tables, and text sometimes are displayed out of order on the PDF. It seems that when the graph or table is too large to fit on a section of the page it just skips over the graph/table and puts whatever comes next to fill the page before inserting the graph/table on the following page.

**Comment by annajzhou** [comment]
@nicholasjhorton We just finished updating the PDF with final edits including the ones Sarah mentioned above, + the feedback you gave us in class on Thursday. We resolved most of the formatting issues, except Table 1 should be on page 3 of the report instead of page 4, and Table 2 needs to go under the "How many employees during this era?" section rather than above.

We would appreciate your help with these formatting issues in rendering from qmd to pdf. Otherwise, the report is all ready for your review.

**Comment by nicholasjhorton** [comment]
See https://github.com/STAT210-S23/Parsons_Paper_Register/commit/c026684ff1dde11b6685a3406af0540dfc912bac for an example of how to create citations in BibTeX within Quarto.

In addition, you'll need to move all of your figures to numbered and captioned figures and the same for tables. Please let me know if you have any questions or run into any issues.

**Comment by annajzhou** [comment]
@nicholasjhorton I pushed changes with updated formatting for all the tables, but I can't figure out how to add figure labels/captions to the ggplot figures in Quarto. When I type " #| label: " for the ggplots code nothing shows up in the pdf output. Would appreciate any help with this

**Comment by annajzhou** [comment]
Closed as final report submitted.

**Comment by nicholasjhorton** [comment]
I've shared feedback under separate cover. Can you please revise and close this issue (anytime before the end of the day on Monday, March 27th)?

**Comment by annajzhou** [comment]
Closed issue as revisions completed.
