### ISSUE TITLE
document the scanning, curation, and archiving of the Parsons Paper Company Register

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#26]
@NahiaP and @kjinsanity could you work to document in a short report the process of scanning (I can flesh this out: please assign me), curating, and making accessible (via the Shiny app and the shared Google Drive) 

You'll want to insert some of the information that was tracked down in #9 and #12.

I would suggest creating a new Quarto file in a new folder in the repo.

A first draft of this work will be due on Friday. I'll need a few days for my part.

**Comment by nicholasjhorton** [comment]
It can also show off https://github.com/STAT210-S23/Parsons_Paper_Register/issues/20

**Comment by nicholasjhorton** [comment]
See https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/ledger_curation/ledger_curation.pdf for a stub.

**Comment by nicholasjhorton** [comment]
is there a plan or outline for this report? It would be very helpful to share this with me in advance of class if possible. I'll do my best to turn around things received as new comments to this issue by noon on Thursday. In any case, please let me know if I can assist as you move forward.

**Comment by NahiaP** [comment]
I have a rough draft where I explain the process of deciding between duplicates, creating the copies to process, and how they were processed. I attached the draft as a pdf to not take up more space.

[Tiff processing.pdf](https://github.com/STAT210-S23/Parsons_Paper_Register/files/10808906/Tiff.processing.pdf)

**Comment by kjinsanity** [comment]
I've begun writing up an outline for this report using the `ledger_curation.qmd` file that @nicholasjhorton created. I will copy over the text @NahiaP wrote over so we can use this central document. I will commit and push after I have finished adding my updates

**Comment by nicholasjhorton** [comment]
These efforts are coming together nicely. Are you able to integrate these into the https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/ledger_curation/ledger_curation.pdf file?

**Comment by kjinsanity** [comment]
Yes, that's the file I am working on. Will commit and push the changes later tonight!

**Comment by kjinsanity** [comment]
> is there a plan or outline for this report? It would be very helpful to share this with me in advance of class if possible. I'll do my best to turn around things received as new comments to this issue by noon on Thursday. In any case, please let me know if I can assist as you move forward.

In reference to @nicholasjhorton's, comment, I have assigned you to the issue and created a rough draft of our report.

**Comment by nicholasjhorton** [comment]
Happy Friday!

Can you please:

1. share an update on what you've been working on since we met yesterday, and
2. add a comment for me in this issue when you are ready for my review?

**Comment by kjinsanity** [comment]
Hi @nicholasjhorton, I've been working on finalizing and editing our report. I filled it out with more details and @NahiaP was able to add more screenshots as well. I believe what we have left is one more look over as well as you to finish the **Scanning Process** section in the report

**Comment by nicholasjhorton** [comment]
I've added in my bits and bobs, see https://github.com/STAT210-S23/Parsons_Paper_Register/commit/24332f8103d7aebcf58342d81a9827a212801bd4

Please be sure to pull before you do anything else!

Note that I've left at least one XX indicating a place where additions are needed based on the feedback I provided you last week.

**Comment by kjinsanity** [comment]
Finished review with @NahiaP , and should be done

**Comment by nicholasjhorton** [comment]
I've shared feedback under separate cover. Can you please revise and close this issue (anytime before the end of the day on Monday, March 27th)?

**Comment by nicholasjhorton** [comment]
final revision to Parsons Paper Company reports due by the end of the day on Wednesday, March 29th: can you please let me know if you have any questions as you finish up your work? @kjinsanity @NahiaP?

**Comment by NahiaP** [comment]
The feedback from the slack pdf was integrated.
