### ISSUE TITLE
create jpeg files from processed tiff files (was: identify workflow to create jpg file from tiff files)

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#3]
These will take the image from the `tiff` folder and create a new jpg in the `jpg` folder

**Comment by nicholasjhorton** [comment]
Note that this assumes that #2 is resolved!

**Comment by nicholasjhorton** [comment]
This can be done via Preview on a Mac.

What settings are ideal to balance image quality and size?

**Comment by nicholasjhorton** [comment]
Note that in issue https://github.com/STAT210-S23/Parsons_Paper_Register/issues/9 @sedelson31 has identified that jpg files are often given in full resolution as well as more user-friendly medium resolution formats. We may want to do that here.

**Comment by nicholasjhorton** [comment]
I suspect that we will want to work to manually curate some set of pages (first 50?) as a way of demonstrating the entire process for this and #2 . Any thoughts?

**Comment by nicholasjhorton** [comment]
This can be done in bulk using Preview. So the remaining work is primarily involved in #19 and #2.

Note that I adopted @NahiaP's `jpeg` suffix. We should decide soon if we want to go with `jpg` instead.

**Comment by nicholasjhorton** [comment]
Considerable progress! See https://github.com/STAT210-S23/Parsons_Paper_Register/tree/main/jpeg

**Comment by nicholasjhorton** [comment]
More progress....https://github.com/STAT210-S23/Parsons_Paper_Register/commit/9eaa7e8fb307d79e85566a0cb1f796f7528351d9

**Comment by nicholasjhorton** [comment]
My automated procedure may not be optimal. See for example the compression on 
[251.jpeg](https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/jpeg/251.jpeg)
 compared to 
[252.jpeg](https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/jpeg/252.jpeg)

**Comment by NahiaP** [comment]
[251.jpeg](https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/jpeg/251.jpeg) definitely has a better resolution, however I don't think that the other is necessarily bad. If needed though, we can take a similar approach of manually splitting it up and manually creating j-pegs.

**Comment by nicholasjhorton** [comment]
Closed via https://github.com/STAT210-S23/Parsons_Paper_Register/commit/b356e64ce5d4038ac289792f4555a4aee61916ba
