### ISSUE TITLE
review documentation of Lucy Allen address

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#32]
@LorraineOloo and @Cheafitz25 can you please add in the documentation of where you found the addresses for Lucy Allen in the ancestry.com work that you did? It would be great to include that here.

I suspect that at least one is from the census records.

Here's the list of locations I'm trying to track down.

<img width="737" alt="Screen Shot 2023-05-02 at 4 09 14 PM" src="https://user-images.githubusercontent.com/530542/235774690-7163524e-f25f-47cd-98ab-f6e75036ca43.png">

**Comment by Cheafitz25** [comment]
Dwight Street in 1869 comes from the 1869 directory which we found in the history room. 236 Maple Street is from the 1883 directory which we also found in the history room. 
Here is the 1869 Directory.
![1869Directory](https://user-images.githubusercontent.com/124196283/236045080-eb8ca2fd-f48d-49b5-bf9d-d5ad93d60b14.jpeg)

As for the 1888-1890 address, I believe Lorraine found that information out.

**Comment by LorraineOloo** [comment]
Here is the info: https://www.ancestrylibrary.com/discoveryui-content/view/473494428:2469?tid=&pid=&queryId=17e343a7598c4eaf780f132e50eb0279&_phsrc=jaS57&_phstart=successSource for 188
https://www.ancestrylibrary.com/discoveryui-content/view/495384509:2469?tid=&pid=&queryId=17e343a7598c4eaf780f132e50eb0279&_phsrc=jaS57&_phstart=successSource for 1889

https://www.ancestrylibrary.com/discoveryui-content/view/501780457:2469?tid=&pid=&queryId=17e343a7598c4eaf780f132e50eb0279&_phsrc=jaS57&_phstart=successSource for 1883

https://www.ancestrylibrary.com/discoveryui-content/view/502197382:2469?tid=&pid=&queryId=17e343a7598c4eaf780f132e50eb0279&_phsrc=jaS57&_phstart=successSource for 187

**Comment by nicholasjhorton** [comment]
![Screen Shot 2023-05-04 at 11 31 58 AM](https://user-images.githubusercontent.com/530542/236256922-6489cc22-b0b8-42f6-8691-4c7496f7a8c0.png)
![Screen Shot 2023-05-04 at 11 32 32 AM](https://user-images.githubusercontent.com/530542/236256927-4e10e482-a6c5-4fa4-8cfc-f8601601975b.png)
![Screen Shot 2023-05-04 at 11 33 06 AM](https://user-images.githubusercontent.com/530542/236256929-03d64da0-daf5-4f49-9240-cd67e0cae640.png)
![Screen Shot 2023-05-04 at 11 33 21 AM](https://user-images.githubusercontent.com/530542/236256931-8ed1bfc2-ce2a-45fc-a005-34fbdfdb2d80.png)

@kjinsanity does this give you what you need for your report?

**Comment by nicholasjhorton** [comment]
If so, can you please close this issue?

**Comment by kjinsanity** [comment]
It does provide good information, but I still can't find where Lucy Allen is in the 1885 Directory. Is there a chance she may have been missed by accident or she just didn't live in Holyoke from 83-87?

**Comment by Cheafitz25** [comment]
Look for Job Allen. We inferred that she still lived with him.

**Comment by kjinsanity** [comment]
![image](https://user-images.githubusercontent.com/10384016/236267928-a8dffa2d-70e6-4c96-948d-21e0ad083530.png)

Here are all the Allens in the 85 directory. Was Job short for anything?

**Comment by Cheafitz25** [comment]
Hm, Job H. Allen was the father. I'm not sure if we looked at the 1885 directory. Maybe its Mss Lucy Allen

**Comment by nicholasjhorton** [comment]
Thanks for the additional information. 

@kjinsanity I wonder if you want to try to identify someone else from @Cheafitz25's existing listing of employees that we can find definitively in the 1885 directory.

**Comment by kjinsanity** [comment]
Would it be possible to send that list over?

I was also thinking I can use the reverse directory aspect to track who lived at Lucy Allen's previous/future residences in 1885 because that might be more related to what a reverse directory should be doing.

**Comment by Cheafitz25** [comment]
I think that is a good idea. Here is a link to the spreadsheet: https://docs.google.com/spreadsheets/d/1P5Bq0hTl4v8frQNiB37XOT_Rat4EfA1FDRCD2f4uDaE/edit#gid=1294815879
Here are some names you could look for that appear a lot in the registry. 
Emma C. Perry, John Flynn, Margaret Haffy, William J. Pomeroy,

**Comment by kjinsanity** [comment]
I was unable to find the other names but some John Flynn, would we happen to know which one it was?

![image](https://user-images.githubusercontent.com/10384016/236296147-a4528d3f-01db-49d1-9a32-9ec2951784d4.png)

**Comment by nicholasjhorton** [comment]
Are you all set with this issue Kevin? I suspect that what you included in your talk will suffice.
