### ISSUE TITLE
explore patterns in employment and groups of employees over time (was: quantify how many employees during this era?)

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#7]
This will require exploring multiple pages that comprise the entire payroll.

**Comment by nicholasjhorton** [comment]
@nicholasjhorton suggestion: stub out an qmd file which summarizes what you find from some of the images.

**Comment by nicholasjhorton** [comment]
@annajzhou have you been able to identify a set of register pages that comprise an entire pay period? Can you find two that are one year apart?

Thanks in advance for any updates on this issue.

**Comment by annajzhou** [comment]
- Looking at the pages, pay periods appear a month long with employees typically getting paid on the 1st of each month
- Based off the spreadsheet from p. 253, most employees work between 20-30 days each pay period, the average is around 27 so most employees work at least 6 days/week
- Pgs. 261-263 appear to comprise an entire pay period for the month of April in 1868
- Pgs. 223-225 and Pgs. 261-263 above are exactly one year apart in the register (April 1st 1867 + April 1st 1868)
- Counted 92 employees in April 1861, 141 employees in April 1863, 128 employees in April 1864, 131 employees in April 1867, 153 employees in April 1868, 153 employees in April 1869 -- average = 133 employees between 1861-1869
- Some pages have a separate section of employees at the bottom under "Repairs" -- I included these names in the counts above

**Comment by nicholasjhorton** [comment]
Cool! Might you be willing to create a simple `qmd` file which summarizes this finding.

**Comment by annajzhou** [comment]
Yes, I created a summary qmd file above and committed it to the main branch (I wasn't sure where/how to upload it?) I would be interested to start working on issue #10 and following a subset of workers to look at employment duration, employment retention,  and any differences before/after the Civil War.

**Comment by nicholasjhorton** [comment]
This is coming together well. 

Just FYI, I moved the file to https://github.com/STAT210-S23/Parsons_Paper_Register/tree/main/payroll_analysis

**Comment by nicholasjhorton** [comment]
@annajzhou might you be able to add the page numbers from the register that you used to calculate the number of employees per pay period in the file https://github.com/STAT210-S23/Parsons_Paper_Register/blob/main/payroll_analysis/parsons_payroll.qmd?

**Comment by kjinsanity** [comment]
Question: Can we figure out what these groups of employees are doing? Looks like they are grouped into different things

**Comment by sedelson31** [comment]
@nicholasjhorton can you please give us the link to the master's thesis that you mentioned (UMass thesis)?

**Comment by annajzhou** [comment]
Yes, I just updated the qmd file with the page numbers. I can also calculate a 9-year average number of employees instead of 6 years if needed.

**Comment by nicholasjhorton** [comment]
@annajzhou thanks! @sedelson31 will also be working with you on next steps for these analyses.

**Comment by nicholasjhorton** [comment]
I split off the review of the Hickey thesis into a separate issue (https://github.com/STAT210-S23/Parsons_Paper_Register/issues/17).

Next steps are to work on refining the questions so that you can briefly update the class about this issue on Tuesday. Does that sound workable? Do you have everything you need to move forward?

**Comment by annajzhou** [comment]
Yes, I updated the qmd file with the new 9-year employee average and a couple other observations.

**Comment by nicholasjhorton** [comment]
I wonder whether it would be helpful to start to create some screenshots to illustrate your methods and results. This is something that we might be able to share with Eileen in advance of our meeting with her next week.

I suspect that using the existing Quarto file to create this technical report would be workable. Thoughts?

**Comment by annajzhou** [comment]
I just updated the qmd file with some screenshots from the register to help with this. Let me know if there's anything else I should add/update.

**Comment by nicholasjhorton** [comment]
Can you also please push changes to the formatted pdf? Thanks in advance, Nick

**Comment by annajzhou** [comment]
Yes, done

**Comment by sedelson31** [comment]
read in google sheet on qmd file which tracks employment by job type for first 6 months and last 6 months of the register

**Comment by nicholasjhorton** [comment]
I look forward to reviewing your draft prior to class. Sometime today can you please:

- push changes to the formatted pdf, and
- add a new comment to let me know you are ready for me to read your revised report?

**Comment by sedelson31** [comment]
@annajzhou could you render to pdf please? For some reason my R will not let me do so

**Comment by nicholasjhorton** [comment]
@sedelson31 Sorry to hear about the complication. I'd be glad to help you troubleshoot in class tomorrow.

**Comment by annajzhou** [comment]
I pushed changes to the revised pdf + qmd file -- I didn't include counts for the last 6 months on the spreadsheet on employment types due to a lack of data after 1861

**Comment by nicholasjhorton** [comment]
@annajzhou I'm not seeing your commit: I don't think that you pushed it.

Note that I added the pdf to the folder (see https://github.com/STAT210-S23/Parsons_Paper_Register/commit/13650b830eddd9f42d8689ded67ba09b9f2f1f74)

**Comment by nicholasjhorton** [comment]
Can you please Slack me with the pdf that you intended to push?

**Comment by annajzhou** [comment]
@nicholasjhorton just Slacked you, sorry about the confusion I'm not sure why I'm getting a merge conflict

**Comment by annajzhou** [comment]
Sarah and I just finished making edits to the report and pushed updates to the pdf + qmd.

**Comment by nicholasjhorton** [comment]
I'm seeing https://github.com/STAT210-S23/Parsons_Paper_Register/commit/bf561068c92bcebd4abf2c7d3ed05ee7eaa2a2af but there was no pdf. 

I've pushed changes to the pdf and will forward to Eileen.

**Comment by nicholasjhorton** [comment]
See https://github.com/STAT210-S23/Parsons_Paper_Register/commit/9b5cd8bd805184c6ceffb440f70d4bd1bdc0a269 for some additional changes that I pushed.

I'm closing this issue (and will open a new issue for future work on this front).
