### ISSUE TITLE
improve Shiny app that displays Parsons register

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#8]
Can we explore what a Shiny app might look like which allows someone to browse the Parsons register? 

This could also incorporate some of the analyses of a particular page, other history of the Parsons Paper company, etc.

**Comment by nicholasjhorton** [comment]
See https://github.com/STAT210-S23/Parsons_Paper_Register/tree/main/shiny_display

**Comment by NahiaP** [comment]
1 idea - leaflet of the tracked addresses

**Comment by nicholasjhorton** [comment]
This is closer to being started: one first step would be to allow a user to pick which one of the jpeg files they want to display.

1. Generate list of files in the https://github.com/STAT210-S23/Parsons_Paper_Register/tree/main/jpeg folder.
2. Create a list of radio buttons with those numbers in the UI
3. Display the first (by default)
4. Add an "About" tab that is stubbed out with placeholder info about the register.

**Comment by kjinsanity** [comment]
https://github.com/STAT210-S23/Parsons_Paper_Register/commit/afef65248b9d2ec8fb3bc2031cfbea3f71cfa87b and https://github.com/STAT210-S23/Parsons_Paper_Register/commit/9794040a56455656e792e1b2b290e81a43e7ab23 are commits for a rough working version of a shiny app

**Comment by nicholasjhorton** [comment]
Very cool, thanks!

**Comment by nicholasjhorton** [comment]
This looks great: see https://r.amherst.edu/apps/nhorton/Parsons-Paper/

**Comment by nicholasjhorton** [comment]
Other ideas to consider for the future:

1. zooming the images?
2. moving to and from the next page?
3. adding some overview about pages (e.g., which are payroll, which are accounting, what years correspond to which pages, etc.)

**Comment by nicholasjhorton** [comment]
Closing this for now: we have a list of potential improvements but these aren't necessary for the time being.

**Comment by nicholasjhorton** [comment]
Kudos to @Cheafitz25 and @kjinsanity for this code (and Stackoverflow before them I believe): see https://github.com/STAT210-S23/Parsons_Paper_Register/commit/9b3cbd23a697853bcbbb2a7685643fad698a889b
