### ISSUE TITLE
identify format to have it added to Digital Commonweatlh

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/Parsons_Paper_Register#9]
In advance of our meeting with Eileen Crosby, it would be helpful to clarify what formats and metadata are needed for submission to the Commonwealth of Massachusetts archive.

http://www.holyokelibrary.org/historydigitalcollection.asp

Question: what are the submission standards and formats needed for this to be added to the Commonwealth archive (@sedelson31 found the name).

Stephanie Capsuto in the library may be resource to tap.

**Comment by nicholasjhorton** [comment]
This will include file formats, how much to crop, rotation, metadata, etc.

**Comment by sedelson31** [comment]
The Commonwealth archive is [here](https://www.digitalcommonwealth.org/)

**Metadata**
The archive's Metadata Requirements & Guidelines are [here](https://membership.digitalcommonwealth.org/metadata-requirements/)

“Metadata records for objects in the Digital Commonwealth repository conform to the [Metadata Object Description Schema](http://www.loc.gov/standards/mods/) (MODS) created by the Library of Congress. The MODS schema provides for robust description of items, and supports the use of a wide variety of controlled vocabularies and content standards.”

"A summary of the requirements for MODS records in the Digital Commonwealth repository -- including usage guidelines for elements, sub-elements, and attributes, as well as recommendations for when to apply content standards and controlled vocabularies -- is available upon request.

A spreadsheet template that can be used to create metadata records conforming to the Digital Commonwealth metadata guidelines and used for batch upload of records and objects into the Digital Commonwealth repository is available upon request."


Item Information can include
- title
- description
- issuing body
- publisher
- date
- format
- genre
- location
- collection (local)
- subjects
- places
- extent
- link to item
- terms of use
- place of origin
- language
- publisher
- notes (object)
- call #

**File format**
Can be JPEG or TIF

On the Digital Commonwealth website, Holyoke Public Library's files are downloadable in three formats
1. Primary (full resolution, uncompressed) - TIF, multi-file ZIP
2. Large (full resolution) - JPEG
3. Medium - JPEG, multi-file ZIP

**Comment by sedelson31** [comment]
Holyoke Public Library also publishes archival material on Archive.org

**Comment by sedelson31** [comment]
I emailed Digital Commonwealth to request the spreadsheet & requirements.

**Comment by nicholasjhorton** [comment]
I wonder if it would be helpful to start up a conversation with Eileen Crosby, who we will meet in two Tuesdays, about the requirements and setup.

We can share a link to the Google Drive (not currently public) and/or the GitHub repo (which is public) if that would be helpful.

**Comment by sedelson31** [comment]
I will email Eileen to ask about metadata requirements.

@nicholasjhorton need the email address

**Comment by nicholasjhorton** [comment]
Can you please share a draft of your proposed email?

See also #12 and #15

**Comment by Cheafitz25** [comment]
Closed in favor of number #12
